FROM node:16.16.0

WORKDIR /starburger_docker/frontend/

COPY . .

RUN npm ci --dev
RUN ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir /starburger_docker/staticfiles/bundles --public-url="./"


