version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - staticfiles:/starburger_docker/staticfiles
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
      - frontend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DATABASE_URL: ${DATABASE_URL}
      YANDEX_API_KEY: ${YANDEX_API_KEY}
      ROLLBAR_KEY: ${ROLLBAR_KEY}
      ROLLBAR_ENVIRONMENT: ${ROLLBAR_ENVIRONMENT}
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8002:8000"
    volumes:
      - staticfiles:/starburger_docker/staticfiles
      - test:/starburger_docker/backend
      - media:/starburger_docker/media

volumes:
  staticfiles:
  media:
  postgres_data:
  test:
