# Generated by Django 3.2.15 on 2023-09-19 16:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
