# Generated by Django 3.2.15 on 2023-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Необработанный'), (2, 'Обрабатывается'), (3, 'Доставляет курьер'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='Cтатус'),
        ),
    ]
