# Generated by Django 3.2.15 on 2023-10-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AddField(
            model_name='product',
            name='restaurants',
            field=models.ManyToManyField(related_name='products', to='foodcartapp.Restaurant', verbose_name='рестораны'),
        ),
    ]
